### ISSUE TITLE
Updating README.md (most likely merging it with CONTRIBUTING.md as well)

### ISSUE THREAD

**Issue by Developer1510** [Developer1510/OpenDataRegistry#11]
We should update the README.md in the github repo, so it will be up to date with our structure and our purpose. We should probably include or modify the info, how the user can contribute their data.

**Comment by Developer1510** [comment]
There is no need for instructions about building or running the project, since this is not indended for the end users. Probably?

**Comment by gmilcinski** [comment]
Indeed you are right.

**Comment by gmilcinski** [comment]
I left the part, which I think might be useful, deleted the rest.
