### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#12]
Please arrange the design to be somehow along the SH design, e.g. following these guidelines:  
https://docs.sentinel-hub.com/api/latest/

make sure to remove AWS logos.  

If there are some things complicated, leave them as they are .

**Comment by Developer1510** [comment]
Gave the files to Klemen and inform him that it's quite high priority. Instructed him about the guidelines and the logos.

**Comment by gmilcinski** [comment]
I think design is OK
