### ISSUE TITLE
Header and footer

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#13]
I modified header and footer here:  
https://github.com/Developer1510/OpenDataRegistry/tree/master/src/partials

but after rebuilding the app, this is not applied.

**Comment by Developer1510** [comment]
Why did you left the title in the "header.hbs" as "Registry of Open Data on AWS"?

**Comment by gmilcinski** [comment]
Ah, I only changed the title, did not see the second mention in the file... I see you updated now, thanks

**Comment by Developer1510** [comment]
Is rebuilt now.

**Comment by gmilcinski** [comment]
Looks good, tnx.
