### ISSUE TITLE
Set-up S3 bucket for Public Collection results

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#2]
Our "Public Collection Registry" is producing a bunch of static files, which are then exposed on the web as a "web application".

This is how the app looks like:  
https://developer1510.github.io/OpenDataRegistry/

These are the static files produces by the build:  
https://github.com/Developer1510/OpenDataRegistry/tree/master/docs

In order to have this as manageable as possible, I would ask you to:
- create a dedicated bucket on our core account, let's call it something like "collections.sentinel-hub.com" (simiarly as we have it for docs.sentinel-hub.com). It should be on eu-central-1.
- add "Hello world HTML" page to it
- configure the account so that it is visible on the web, under domain collections.sentinel-hub.com
- configure cloudfront etc.
- set up the rights, so that grega.milcinski+sh_library@sinergise.com AWS user (634240407771, credentials in keeper) will be able to full manage this S3 (write, delete, read, list, etc.)

CC: @Developer1510

**Comment by gmilcinski** [comment]
The bucket should be on eu-central-1

**Comment by rkosir** [comment]
This was done, it will take some time for DNSes for bucket routing is properly refreshed

**Comment by gmilcinski** [comment]
@rkosir - can you please setup the S3 to be accessible by the sh_library accunt?  

set up the rights, so that grega.milcinski+sh_library@sinergise.com AWS user (634240407771, credentials in keeper) will be able to full manage this S3 (write, delete, read, list, etc.)

**Comment by Developer1510** [comment]
It's under control now

**Comment by gmilcinski** [comment]
@rkosir - there seems to be an issue with the cache. I updated (and rebuilt) the site yesterday afternoon and it is still the same:  
https://collections.sentinel-hub.com/global-land-cover/  
(should have bands in the table)  

Can you check if this can be sped up somehow?

**Comment by rkosir** [comment]
Default cache TTL set to 1h
