### ISSUE TITLE
Move the project under Sinerigse's control

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#4]
At the moment this project is publicy visible, which does not make it feasible for internal works.

For "Public registry", e.g. for source documentation files, do use:  
https://github.com/sentinel-hub/public-collections/   
Feel free to move the existing content there to some "archive" folder on the same github. 

For the "internal part", e.g. the application.  
Ideally this would be moved to our internal GitLab (company's).  
If it has to be on GitHub, move it to 
https://github.com/sentinel-hub/PublicCollectionsRegistry  
and make it private. 

CC: @rkosir

**Comment by Developer1510** [comment]
@gmilcinski Please add "developer1510" as the collaborator on https://github.com/sentinel-hub/public-collections/ and https://github.com/sentinel-hub/PublicCollectionsRegistry so I will be able to manage the data there.

**Comment by Developer1510** [comment]
As I understand, you don't want the same repo for both things? It will complicate things if I now split back both.

**Comment by Developer1510** [comment]
Also, I don't see a need to backup the existing files in the first repo, as completely the same content is used in the new repo as well.

**Comment by gmilcinski** [comment]
You should have received the invitation, granting Admin level.

**Comment by gmilcinski** [comment]
This repo will be used only for "new" thing, i.e. Open Data Repository.  
The existing content will be "migrated" to the new thing as soon as it is running. There is one new collection there ("water bodies").  

In order to avoid you handling the migration (we can ask SH VAS to do so), please do:  
- "rename" the existing "collections" folder to "collections_backup"  
- move existing "README.md" in "collections_backup" as well  
- copy all ["new" material](https://github.com/Developer1510/OpenDataRegistry) to "target repo" (https://github.com/sentinel-hub/public-collections)

Once the new system is in place, I will ask SH VAS to migrate the remaining content from collection_archive to new system and delete the collection_archive folder.

**Comment by Developer1510** [comment]
Done
