### ISSUE TITLE
Band information

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#5]
Can you redefine the part rleated to "Band information" so that these will be shown as a simple table, rather than just a string?

See as an example this:  
https://github.com/sentinel-hub/public-collections/tree/main/collections/global-land-cover#band-information
vs.   
https://developer1510.github.io/OpenDataRegistry/global-land-cover/

I would keep it a simple two-column table.

**Comment by Developer1510** [comment]
There is now a possibility to display tabelaric data. 

See the structure for "TabelaricData" here:
- https://github.com/Developer1510/OpenDataRegistry/blob/master/data-sources/awslabs-open-data-registry/datasets/sentinel-s2-l2a-mosaic-120.yaml

You can define any possible table with a defined list of header names.

Note that "Name" is used in YAML for the cell value lookup, while "Title" is displayed in HTML

**Comment by Developer1510** [comment]
Also note, that currently there is no CSS for the tables, so the table is without any borders or background colors. The final design will include this, of course.

This is how it looks now:
- https://developer1510.github.io/OpenDataRegistry/sentinel-s2-l2a-mosaic-120/

I left the old "BandInformation" still there in YAML. If you will remove it, it will not be displayed anymore. So you can fill now the actual table cell values.

**Comment by gmilcinski** [comment]
Cool, looks good.
