### ISSUE TITLE
Custom scripts part

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#6]
I would want to have a section, where one could list (optional) one or many custom scripts, in a simlar way as one can list [publications](https://developer1510.github.io/OpenDataRegistry/sentinel-s2-l2a-mosaic-120/)  .

I added an exemplary code block in:  
https://github.com/Developer1510/OpenDataRegistry/blob/master/data-sources/awslabs-open-data-registry/datasets/sentinel-2-l1c.yaml

**Comment by Developer1510** [comment]
It's implemented, in a way that if you provide a list in YAML, it will be a bulleted list in HTML, but if you provide a single entity, it will be a single link.

For example:

```
CustomScripts:
    Title: blabla
    URL: blabla
```

will produce a single link,
while:

```
CustomScripts:
  - Title: blabla
     URL: blabla
  - Title: haha
     URL: haha
```
will produce bulleted list

**Comment by Developer1510** [comment]
A "working" example is in "sentinel-2-l1c.yaml"
