### ISSUE TITLE
Additional information 

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#7]
Some collections will have (optionally) some more elaborate information. I would organise these in a dedicated folder, with the same name as th ecollection itself. Within that folder there should be (mandatory) one file (index.html or readme.md) and then as many other files as needed, linked from the main file.  

This can already be seen e..g here:   
https://github.com/sentinel-hub/public-collections/tree/main/collections/global-land-cover

However, this now links to GiThub. Ideally this page would be open directly in the "Public Collections" app.

**Comment by Developer1510** [comment]
If I understand correctly, you want to generate HTML from the MD file and link to this new HTML file from the dataset details page?

If yes, then it should be a MD file, so we can contain it inside a nice HTML container, like for everything else.

The subfolder doesn't need to have the same name, since the subfolder name for this ExtraInformationFolder will be written in the YAML file. But it's nice to have the matching name, so it's easier to manage.

**Comment by gmilcinski** [comment]
We could even ask users to submit "additional info" in HTML, if this would be easier. MD is probalby easier to maintain on the users' side, so if your option is simple to implement, it would be better. 

True on the subfolder name, but woudl still insist on the pattern, so that it is well organised.

**Comment by Developer1510** [comment]
HTML can make a garbage, better to force the users to prepare MD file. The Node.js builder already contains functions to convert MD to HTML.

With HTML, the users would or could play with CSS and styles, and I wouldn't allow that, as it's probably meant to have a common visual style. But they can link external webpages with their own design, if they want to.

**Comment by gmilcinski** [comment]
Agreed. Let's stick to MD.

**Comment by Developer1510** [comment]
It's done partially. Example in Corine. Instead of AdditionalInformation, you have to use AdditionalInformationExternal.

By partially, it means that the produced HTML is not yet contained in a nice container.

**Comment by Developer1510** [comment]
Now even encapsulated with the nice HTML container. Please check if ok.

**Comment by gmilcinski** [comment]
Looks good.  
What is the rule? there needs to be README.MD file and you link it as README.HTML?

**Comment by Developer1510** [comment]
there can be ```<anyname>.md``` or .MD, as its name is written in YAML

**Comment by gmilcinski** [comment]
cool

**Comment by Developer1510** [comment]
Example:

```
AdditionalInfoExternal:
    Title: Additional info 
    Path: corine-land-cover/README.MD
```
This will copy all the source files from "corine-land-cover", except the MD file, which will be converted into HTML
