### ISSUE TITLE
See all datasets managed by

### ISSUE THREAD

**Issue by gmilcinski** [Developer1510/OpenDataRegistry#8]
This functionality is currently not working as it links to AWS Registry.  

If it is not too complex, do fix it. If not, remove it.

**Comment by Developer1510** [comment]
Where does it need to point to? "Managed by Sinergise", but what about the URL? Sinergise webpage?

**Comment by gmilcinski** [comment]
This is supposed to do filtering by the "managed by" (same as it is for tags, etc.). So it shows all datasets that have managed by individual organisation

**Comment by Developer1510** [comment]
Think it might be working now, but  cannot test, since all 4 datasets are managed by the same entity, so the filter doesn't show any differences.

**Comment by gmilcinski** [comment]
Let's close this for now, will re-open if/once we see it is not working.
